### ISSUE TITLE
Issue with intellisense in 'regular' text.

### ISSUE THREAD

**Issue by cfjedimaster** [pcbowers/alpine-intellisense#4]
I'm seeing the extension be a bit aggressive in terms of suggestions when typing. So for example, on a page w/ no JS at all, I typed:

```html
<p>
Hello world.
</p>
```

When I typed the period at the end, I got:

![image](https://user-images.githubusercontent.com/393660/175396176-f2946caa-2964-4f9f-b015-4cf77b38e61b.png)

As I'm a fast typer, I ened up with:  `Hello world.alt`. 

Any reason why it is prompting for stuff with just a period?

**Comment by pcbowers** [comment]
This is a feature of snippets. Since snippets are tied to file types (extensions), you can disable them if you like. There is a setting for this extension (`alpine-intellisense.settings.languageScopes`); as long as you remove HTML, this will remove these snippets. I'm going to close this for now since this is avoidable with that setting, but let me know if you have a better solution!
