### ISSUE TITLE
The documentation feature only works for HTML files

### ISSUE THREAD

**Issue by Random72IsTaken** [pcbowers/alpine-intellisense#7]
Greetings, and thank kindly you for the amazing extension.

I noticed that the documentation feature, which I consider to be the best out of the extension's, doesn't work for any other file types, even when defined using the extension setting.

Is there any easy solution to make that documentation popup shows up for Blade files, after setting it using the following code?

```json
"alpine-intellisense.settings.languageScopes": "blade",
```

**Comment by pcbowers** [comment]
@Random72IsTaken I would love for this to be a feature, but I don't think it's currently possible. I am using something called customData which is built into VS Code's HTML language server. Most languages that add syntax to HTML (i.e. PHP) define in their syntax what is HTML and what isn't, which allows this extension to work for them. I'm guessing based on your issue that blade doesn't do this.

I'm going to close this for now since this would require more changes than I would know how to implement. That said, if you have a fix, I'm open to PR's and would love to add more support for other langauges!
